### ISSUE TITLE
Demo site only handles a single key/value pair

### ISSUE THREAD

**Issue by PixelPartner** [billstclair/elm-localstorage#1]
I tried your example / live-demo website and could not **set|get|list** more than **one** entry.
So I assume your package is lacking proper testing or the demo is buggy.
I used latest vanilla Firefox (60.0.1) on Windows 8.1 64.

**Comment by billstclair** [comment]
I just now saw this. Sorry to take so long to respond.

You can set/get as many items as you want, at least in my version of Firefox. Note that the "List" button returns only the keys that begin with the "Key", so if you want to see all of them, clear that before clicking "List".

It works for me in Firefox 61.0.1 and Chrome 68.0.3440.106 and Brave 0.23.105 on MacOS 10.13.6 (High Sierra). If you still can't get it to work in your configuration, I'll try it on my Windows 8 laptop.
